### ISSUE TITLE
Update README installation instructions to reference `@sanity/dashboard@studio-v3`

### ISSUE THREAD

**Issue by franknoirot** [sanity-io/dashboard#1]
I got a "No matching version found" error when trying to install the v3 developer preview using `npm install --save @sanity/dashboard@sanity-v3`.

Looking at npm it appears the tag should be updated to `@studio-v3`, but I may be wrong.

**Comment by stipsan** [comment]
I don't know if/when this was changed but as far as I can tell the README now refers to `studio-v3` and not `sanity-v3` 😄
