### ISSUE TITLE
ESM imports throwing errors

### ISSUE THREAD

**Issue by bradymwilliams** [sanity-io/dashboard#48]
I'm using the [Epic Stack for Remix](https://github.com/epicweb-dev/epic-stack) but having issues importing plugins for use in the studio

I can import the Vision and Desk plugins just fine but when I import dashboard or any others I get errors

`import { dashboardTool } from '@sanity/dashboard'`
results in:
```
TypeError: styled is not a function
TypeError: styled is not a function
```

`import { dashboardTool } from '#node_modules/@sanity/dashboard/lib/index.esm.js'`
results in:
```
SyntaxError: The requested module '@sanity/dashboard' does not provide an export named 'dashboardTool'
```

Also can't use `const dashboardTool = require('@sanity/dashboard')`

**Comment by rexxars** [comment]
Should be fixed in [v4](https://github.com/sanity-io/dashboard/releases/tag/v4.0.0)
