### ISSUE TITLE
Wrong "Invite members" link in "Project users" widget 

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/dashboard#53]
**Describe the bug**

Hi guys.
In my Studio I just installed the "Project users" widget and when I clicked on "Invite members" I was sent to a non-existing page in my project dashboard.  Instead of `/members` URL I ended up on `/team/invite` URL and got "Oops! Page not found. The content you tried to access does not exist."

**To Reproduce**

1. Install `projectUsersWidget` in `sanity.config.js`
2. Click on 'Dahsboard' in your Studio
3. Find the "Project users" widget and click on "Invite members"
4. See 404 page

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.19.2 (latest: 3.19.3)
@sanity/cli                   3.19.2 (latest: 3.19.3)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/vision                3.19.2 (latest: 3.19.3)
sanity                        3.19.2 (latest: 3.19.3)
```

**What operating system are you using?**
elementaryOS 6.1 (based on Ubuntu 20.04.6 LTS)

**Which versions of Node.js / npm are you running?**

```
npm: 10.2.1
nodejs: v18.18.0
```

Cheers.

**Comment by rexxars** [comment]
Fixed in [v4](https://github.com/sanity-io/dashboard/releases/tag/v4.0.0)
