### ISSUE TITLE
Support for Styled Components v6

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/dashboard#57]
**Describe the bug**

Please update to support Styled Components v6 which now comes as a default in new Sanity CLI projects.

Cheers.

**Comment by Jay-Ferguson** [comment]
The fact that this has not been addressed is an issue, I do appreciate that this is free software and would like to help not hurt. If sanity is going to offer a tool like this to expand the functionality of the core CMS, I would I hope they would maintain it. This dashboard tool offers key features like Vercel and Netilify deployments (especially when bulk publishing is not offered in the default studio). Running an outdated version of a styling dep that does not work with the core studio should not be required to have a deployment button or other non style related functionality working. Using plain css or something with fewer peer deps would keep the integration far simpler, is styled components really needed for this to function? If anyone with more knowledge of the library code wants to give instructions on the process to integrate styled-components v6 I would happy to do what I can.

**Comment by rexxars** [comment]
Try out `@sanity/dashboard@v4`! https://github.com/sanity-io/dashboard/releases/tag/v4.0.0

**Comment by WebShapedBiz** [comment]
Thank you @rexxars for your time and effort.
